mockserver:
  base-url: "https://jme-dev.ingress.nivel.bazg.admin.ch/${spring.application.name}"

jeap:
  web:
    tls:
      enabled: true
  logging:
    platform: cloudwatch

management:
  server:
    base-path: ${server.servlet.context-path}
    port: 52873
    ssl:
      enabled: false
