management:
  server:
    port: 8082
    base-path: /process-archive
jeap:
  messaging:
    kafka:
      systemName: jme
      # The RHOS cluster configuration is made via the gitops repository
  monitor:
    prometheus:
      secure: false
  logging:
    platform: rhos
  swagger:
    status: OPEN
  security:
    oauth2:
      resourceserver:
        authorization-server:
          issuer: "https://bit-jme-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch/jme-process-archive-auth-scs"
          jwk-set-uri: "${jeap.security.oauth2.resourceserver.authorization-server.issuer}/.well-known/jwks.json"
  web:
    tls:
      enabled: false

  vault:
    # Vault server URL for the dev environment
    url: https://vault-bfdcbaf9-e8b9-47c7-b296-5b0b0381aeb8.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch
    kv:
      backend: bit-jme-d
    kubernetes:
      role: jme-process-archive-service-role
      kubernetes-path: jwt-p-szb-ros-shrd-npr-01
  crypto:
    vault:
      default-secret-engine-path: "transit/${jeap.vault.system-name}"
      default-encryption-key-cache-expiry-duration: 1h # Default applies if not set
      default-decryption-key-cache-expiry-duration: 6h # Default applies if not set
      encryption-key-max-cache-size: 100 # Default applies if not set
      decryption-key-max-cache-size: 50000 # Default applies if not set
      keys:
        jme-process-archive-example-key:
          secret-engine-path: "transit/jme"
          key-name: "jme-process-archive-example-s3-key"
  processarchive:
    objectstorage:
      connection:
        region: "us-east-1"
        accessUrl: ${jeap.s3.client.endpoint-url}
        accessKey: ${jeap.s3.client.access-key}
        secretKey: ${jeap.s3.client.secret-key}
      storage:
        bucket: bit-jme-processarchive-lockable-obs
        prefix-mode: DAY

spring:
  datasource:
    hikari:
      schema: data
  jpa:
    properties:
      hibernate:
        default_schema: data
  flyway:
    # Flyway creates automatically the default schema if it doesn't exist
    default-schema: data

database-migration:
  init-container: ${IS_INIT_CONTAINER_EXECUTION}

decree-document.archive.uri: "https://bit-jme-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch/jme-process-archive-resource-service/api/archive/decreedocuments/{id}"
diagram.archive.uri: "https://bit-jme-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch/jme-process-archive-resource-service/api/diagrams/{id}/archival?version={version}"
