spring:
  cloud:
    vault:
      enabled: true
  application:
    name: jme-process-archive-inspection-service

server:
  servlet:
    context-path: /${spring.application.name}

jeap:
  vault:
    system-name: jme
  web:
    tls:
      enabled: false