spring:
  cloud:
    vault:
      enabled: true
management:
  server:
    port: 8082
    base-path: /${spring.application.name}
jeap:
  vault:
    # Vault server URL for the dev environment
    url: https://vault-bfdcbaf9-e8b9-47c7-b296-5b0b0381aeb8.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch
    kv:
      backend: bit-jme-d
    kubernetes:
      role: jme-process-archive-inspection-service-role
      kubernetes-path: jwt-p-szb-ros-shrd-npr-01
  crypto:
    vault:
      keys:
        jme-process-archive-example-key:
          secret-engine-path: "transit/jme"
          key-name: "jme-process-archive-example-s3-key"
  s3:
    bucket-names:
      processarchive-bucket: 'bit-jme-processarchive-lockable-obs'
    bucket-management:
      enabled: true
  monitor:
    prometheus:
      secure: false
  logging:
    platform: rhos
  swagger:
    status: open
  web:
    tls:
      enabled: false
jme:
  processarchive:
    objectstorage:
      connection:
        region: "us-east-1"
        accessUrl: ${jeap.s3.client.endpoint-url}
        accessKey: ${jeap.s3.client.access-key}
        secretKey: ${jeap.s3.client.secret-key}
